default_install_hook_types: [commit-msg]
repos:
- repo: local
  rev: v1.3.6
  hooks:
    - id: check-commit-message
      name: check-commit-message
      entry: ./check-commit-message.sh
      language: script
      pass_filenames: false